# Generated by Django 4.0.3 on 2022-04-03 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('bno', models.IntegerField(primary_key=True, serialize=False, verbose_name='图书编号')),
                ('type', models.CharField(max_length=20, verbose_name='类别')),
                ('name', models.CharField(max_length=32, verbose_name='书名')),
                ('publisher', models.CharField(max_length=32, verbose_name='出版社')),
                ('year', models.DateField(verbose_name='年份')),
                ('author', models.CharField(max_length=32, verbose_name='作者')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='价格')),
                ('total', models.SmallIntegerField(verbose_name='总藏书量')),
                ('stock', models.SmallIntegerField(verbose_name='当前库存')),
            ],
        ),
        migrations.CreateModel(
            name='manager',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
                ('name', models.CharField(max_length=32, verbose_name='姓名')),
                ('contact', models.IntegerField(verbose_name='联系方式')),
            ],
        ),
    ]
