# Generated by Django 4.0.3 on 2022-04-04 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='cno',
            field=models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='卡号'),
        ),
    ]
