# Generated by Django 4.0.3 on 2022-04-04 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_newbooks_alter_book_stock_alter_book_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newbooks',
            name='file',
            field=models.FileField(upload_to='', verbose_name='上传'),
        ),
    ]
