# Generated by Django 4.0.3 on 2022-04-04 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_alter_newbooks_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='bno',
            field=models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='图书编号'),
        ),
    ]
