# Generated by Django 4.0.3 on 2022-04-05 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_alter_book_bno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='id',
            field=models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='borrow_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrow_time', models.DateField(verbose_name='借期')),
                ('return_time', models.DateField(verbose_name='预计还期')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.book', verbose_name='书号')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.card', verbose_name='卡号')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.manager', verbose_name='经手人')),
            ],
        ),
    ]
